### ISSUE TITLE
Hacktoberfest: New categories / resources

### ISSUE THREAD

**Issue by closebracket** [CodheadClub/AwesomeResources#44]
We're looking to expand our existing student resources list categorieswith resources as well as generate new categories, some of the suggested categories are as follows:

- Artificial intelligence 
- Electronics
- Data Mining
- Blockchain
- Quality Assurance & Testing
- Academic papers 
- Data sets & APIs
- Opensource projects 
- DevOps
- Mathematics
- Other University Resources

Please ensure you abide by the Hacktoberfest rules in the CONTRIBUTING.md file.

**Comment by rhondakremer** [comment]
Hi! Can I start a kubernetes section?

**Comment by sbrl** [comment]
Hmmm, kubernetes isn't the only technology there @rhondakremer. Perhaps a more general title such as "cloud technologies" or something about scalable computing / clustering?

**Comment by rhondakremer** [comment]
@sbrl how about DevOps and I can add Kubernetes, Docker, and Jenkins sections? Not all inclusive but a start :)

**Comment by sbrl** [comment]
"DevOps" sounds like a good section name :-)
