### ISSUE TITLE
Competitive Programming Category

### ISSUE THREAD

**Issue by aaryan2134** [CodheadClub/AwesomeResources#47]
Can I add a Competitive Coding Category in this Repo?
I had a quite a few resources on it.
Thanks!

**Comment by closebracket** [comment]
Hello!

Yes, that would be more than welcome. Please put the resources as a sub category under programming.

Thank you.

**Comment by aaryan2134** [comment]
That's great!

**Comment by aaryan2134** [comment]
Hi! I have added the subcategory as a PR. https://github.com/FreesideHull/StudentResources/pull/49

**Comment by closebracket** [comment]
Closing this issue as the PR has been merged.
